// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3o-R4pNbgcGSlW8NM6ZfejceBgwp0qZ0',
    appId: '1:976061861367:web:6f8f7a31643bd60e2af2f2',
    messagingSenderId: '976061861367',
    projectId: 'openheartextension-b22e5',
    authDomain: 'openheartextension-b22e5.firebaseapp.com',
    databaseURL:
        'https://openheartextension-b22e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openheartextension-b22e5.appspot.com',
    measurementId: 'G-R0DQ6T6P2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDovU0-V3e6-Me56ji8zgk-Yea31sIj8_I',
    appId: '1:976061861367:android:869168053af4a7c12af2f2',
    messagingSenderId: '976061861367',
    projectId: 'openheartextension-b22e5',
    databaseURL:
        'https://openheartextension-b22e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openheartextension-b22e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkEopWdJzGzdAvyuj2TKnWh66H45KcI0',
    appId: '1:976061861367:ios:c6bccf2b5dc9b1dd2af2f2',
    messagingSenderId: '976061861367',
    projectId: 'openheartextension-b22e5',
    databaseURL:
        'https://openheartextension-b22e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openheartextension-b22e5.appspot.com',
    androidClientId:
        '976061861367-airlqggioapfggdjg9c5jhqedohm6sdb.apps.googleusercontent.com',
    iosClientId:
        '976061861367-s881nr7n7r42ksgsuj45qg46emorgtea.apps.googleusercontent.com',
    iosBundleId: 'com.app.peJeHealthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooSUGSf63Ghq02_iIhtnmwMDs4HlWS6c',
    appId: '1:976061861367:ios:c6bccf2b5dc9b1dd2af2f2',
    messagingSenderId: '976061861367',
    projectId: 'openheartextension-b22e5',
    databaseURL:
        'https://openheartextension-b22e5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'openheartextension-b22e5.appspot.com',
    androidClientId:
        '976061861367-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
    iosClientId:
        '976061861367-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.tests',
  );
}
